### PR TITLE
Bug 30952: (follow-up) Proposed reworking of catalog header menu link

### PR DESCRIPTION
**Pull request by oleonard**

### CODE REVIEW

**Comment by oleonard** [comment]
I'm not sure why the hover event is not working... The dropdown link is supposed to be highlighted when you hover the "Search" link.

**Comment by mrenvoize** [comment]
Relates to issue #46

**Comment by jajm** [comment]
Cherry-picked into the main branch, thanks

**Comment by jajm** [comment]
> I'm not sure why the hover event is not working... The dropdown link is supposed to be highlighted when you hover the "Search" link.

Is it really supposed to do that ? On master it doesn't work like that

**Comment by oleonard** [comment]
> Is it really supposed to do that ? On master it doesn't work like that

Will be fixed by Bug 31653: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=31653

**Pull request closed without merging**
